export const CREATE_COURSE = "CREATE_COURSE";
export const LOAD_COURSES_SUCCES = "LOAD_COURSES_SUCCES";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const UPLOAD_COURSES_SUCCESS = "UPLOAD_COURSES_SUCCESS";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";